name: Build and Upload Expo APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Login to Expo
        run: echo $EXPO_TOKEN | eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK
        run: eas build --platform android --non-interactive --profile preview

      - name: Download APK
        run: |
          APK_URL=$(eas build:list --json | jq -r '.builds[0].artifacts.buildUrl')
          wget -O app-release.apk "$APK_URL"

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app-release.apk